# 2. Preliminaries

## 2.1 Data Manipulation

In [1]:
import torch

In [7]:
x = torch.arange(12, dtype=torch.int64)

In [8]:
torch.exp2(x)

tensor([1.0000e+00, 2.0000e+00, 4.0000e+00, 8.0000e+00, 1.6000e+01, 3.2000e+01,
        6.4000e+01, 1.2800e+02, 2.5600e+02, 5.1200e+02, 1.0240e+03, 2.0480e+03])

In [9]:
torch.exp(torch.randn(2,2,2, dtype=torch.float32))

tensor([[[0.6771, 0.4881],
         [0.1972, 3.2769]],

        [[0.5205, 1.3604],
         [1.2545, 8.2746]]])

In [10]:
x = torch.arange(12, dtype=torch.float32).reshape((3,4))
torch.cat((x,x), dim=0), torch.cat((x,x), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 0.,  1.,  2.,  3.,  0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.,  4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.,  8.,  9., 10., 11.]]))

In [11]:
x = torch.bernoulli(torch.Tensor(5, 5).fill_(0.5))
y = torch.bernoulli(torch.Tensor(5, 5).fill_(0.5))
x == y

tensor([[ True,  True, False, False,  True],
        [False,  True,  True, False,  True],
        [False,  True, False,  True, False],
        [False, False, False,  True, False],
        [False,  True, False, False,  True]])

In [12]:
x.sum()

tensor(8.)

## 2.2 Data Preprocessing

In [2]:
import os

os.makedirs(os.path.join('.', 'data'), exist_ok=True)
data_file = os.path.join('.', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('''NumRooms,RoofType,Price
NA,NA,127500
2,NA,106000
4,Slate,178100
NA,NA,140000''')

In [3]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000
